Mutation:
  type: "object"
  config:
    fields:
      user_signup:
        type: "UserPayload!"
        args:
          input:
            type: "SignupCredentials!"
        resolve: "@=mutation('signup', [args['input']])"
        description: >
          Sign up User & return itself.

      user_edit:
        type: "User!"
        args:
            user:
              type: "UserInput!"
            userId:
              type: "Uuid"
        resolve: "@=mutation('userEdit', [args['user'], args['userId']])"
        description: >
          Edit User infos.

      place_new:
        type: "Place!"
        args:
            place:
              type: "PlaceInput!"
        resolve: "@=mutation('placeNew', [args['place']])"
        description: >
          Add new place.

      place_edit:
        type: "Place!"
        args:
            place:
              type: "PlaceInput!"
            placeId:
              type: "Uuid"
        resolve: "@=mutation('placeEdit', [args['place'], args['placeId']])"
        description: >
          Edit Place infos.

      place_theme:
        type: "Theme!"
        args:
            theme:
              type: "ThemeInput!"
        resolve: "@=mutation('placeTheme', [args['theme']])"
        description: >
          Edit theme infos.

      place_link_theme:
        type: "Place!"
        args:
          placeId:
             type: "Uuid!"
          themeId:
             type: "Uuid!"
        resolve: "@=mutation('placeLinkTheme', [args['placeId'], args['themeId']])"