Place:
  type: "object"
  config:
    fields:
      id:
        type: "Uuid!"
      name:
        type: "String!"
      address:
        type: "String!"
      handicap_moteur:
        type: "String!"

PlaceInput:
  type: "input-object"
  config:
    fields:
      name:
        type: "String!"
      address:
        type: "String!"
      handicap_moteur:
        type: "String!"
