Query:
  type: "object"
  config:
    fields:
      user:
        type: "User"
        args:
          id:
            type: "Uuid!"
        resolve: "@=resolver('entity', ['User', args['id']])"

      users:
        type: "[User]!"
        resolve: "@=resolver('entities', ['User'])"

      places:
        type: "[Place]!"
        resolve: "@=resolver('entities', ['Place'])"

      themes:
        type: "[Theme]!"
        resolve: "@=resolver('entities', ['Theme'])"
