User:
  type: "object"
  config:
    fields:
      id:
        type: "Uuid!"
      email:
        type: "String!"
      firstName:
        type: "String!"
      lastName:
        type: "String!"
      createdAt:
        type: "Datetime!"
      updatedAt:
        type: "Datetime!"

SignupCredentials:
  type: "input-object"
  config:
    fields:
      email:
        type: "String!"
      firstName:
        type: "String!"
      lastName:
        type: "String!"

UserPayload:
  type: "object"
  config:
    fields:
      user: 
        type: "User!"

UserInput:
  type: "input-object"
  config:
    fields:
      email:
        type: "String!"
      firstName:
        type: "String!"
      lastName:
        type: "String!"
